[project]
name = "m5-writeapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "platformio>=6.1.18",
    "streamlit>=1.52.2",
]
